### ISSUE TITLE
new app getting  'Not Found'

### ISSUE THREAD

**Issue by opensussex** [joelesko/owl#2]
Hello

I started playing around with Owl today - and after reading the docs thought it was a great idea / concept

so I got in installed and set up - all seemed ok - but when I did 

`owl server`
and went to the local url - I got a 'Not Found' in the browser

taking a look at it I noticed that on line 116 (of lib/core/Owl.php) there was a `return false` - if I remove this then it all works fine 

the full bit of code is 

```
        if (Owl::isMode('testServer')) {
            // return static assets
            if (file_exists($_SERVER["SCRIPT_FILENAME"])) {
                return false;
            }
        }
```

what was the intention here?

**Comment by joelesko** [comment]
Thanks for the report!

The built-in PHP web server sends all static asset requests to OWL.  OWL then assumes that if the file exists at the given path, that it's static and should just exit.  

Normal page requests are assumed to NOT exist in the Document Root, and should be handled by the router.  This mimics the mod_rewrite logic in the .htaccess that is used when Apache is running. (i.e. server existing files as-is; everything else is handled by the router.)

Can you send the output of `$_SERVER["SCRIPT_FILENAME"]`, and see if it exists in your document root?

From the PHP docs:
> If a PHP file is given on the command line when the web server is started it is treated as a "router" script. The script is run at the start of each HTTP request. If this script returns FALSE, then the requested resource is returned as-is. Otherwise the script's output is returned to the browser.

Thanks

**Comment by opensussex** [comment]
/home/graham/Dev/projects/owl/test/estimate/owlApp.php

that's the file - so am I basically calling the `owl server` in the wrong place?

**Comment by joelesko** [comment]
Interesting.  Looks like testServer mode is being inconsistent about what it reports in SCRIPT_FILENAME. 

* What PHP version are you using?
* Can you send the output of `print_r($_SERVER); exit();` just before the `file_exists` check?

Thanks!

**Comment by opensussex** [comment]
Hello 

php version

```
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

out put of 
print_r($_SERVER);

```
Array ( [DOCUMENT_ROOT] => /home/graham/Dev/projects/owl/test/estimate [REMOTE_ADDR] => 127.0.0.1 [REMOTE_PORT] => 42770 [SERVER_SOFTWARE] => PHP 7.0.18-0ubuntu0.16.04.1 Development Server [SERVER_PROTOCOL] => HTTP/1.1 [SERVER_NAME] => localhost [SERVER_PORT] => 8888 [REQUEST_URI] => / [REQUEST_METHOD] => GET [SCRIPT_NAME] => / [SCRIPT_FILENAME] => /home/graham/Dev/projects/owl/test/estimate/owlApp.php [PHP_SELF] => / [HTTP_HOST] => localhost:8888 [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0 [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5 [HTTP_ACCEPT_ENCODING] => gzip, deflate [HTTP_CONNECTION] => keep-alive [HTTP_UPGRADE_INSECURE_REQUESTS] => 1 [REQUEST_TIME_FLOAT] => 1501917359.7468 [REQUEST_TIME] => 1501917359 ) 
```

**Comment by joelesko** [comment]
I'm not sure why your version is reporting `SCRIPT_FILENAME` differently.  On my MBP, v5.6 and v7.1 both handle it as expected.

Looks like I'll have to write a patch that constructs the full requested filepath manually, instead of relying on `SCRIPT_FILENAME`.

For now, I'd go with your workaround.  If you need to serve images, you can just return `false` if `$_SERVER["REQUEST_URL"]` matches e.g. `'.png'`.

**Comment by opensussex** [comment]
great thanks for the work around I'll have a play.
