### ISSUE TITLE
hitting the Remote Origin Not Allowed with a form post

### ISSUE THREAD

**Issue by opensussex** [joelesko/owl#3]
Hello

So - I noticed there was a todo in the  isCrossOrigin() function in `vendors/owl/owl/lib/modules/Web.php`

The todo was to check the referrer, and I've presumed that it's to check it against the host.

for my purpose I've just done

```
               if (strpos($referrer, $host)) {
                   $this->isCrossOrigin = false;
               } else {
                   $this->isCrossOrigin = true;
               }
```

not sure if you're allowing pull requests? but I've forked your repo as it was a blocker for me for what I needed to do.

**Comment by joelesko** [comment]
Yep, that's it.  Happy to take it as a pull request.  Thanks!

**Comment by opensussex** [comment]
I'll make a PR later this evening for that then. - have to say I am really enjoying using owl !

**Comment by opensussex** [comment]
https://github.com/joelesko/owl/pull/4 << PR for this.

**Comment by joelesko** [comment]
Merged.  Thanks!
